### ISSUE TITLE
2D Character Rendering

### ISSUE THREAD

**Issue by drgomesp** [drgomesp/midgarts#6]
We need to support rendering of all kinds of character sprites, considering initially - but not limited to - the following requirements:

- [x] Body
- [x] Head and rest of sprites
- [ ] Character actions (idle, sit, walk, attack, etc) and their animations
- [x] Directions

The current implementation in the examples shows a very naive way of rendering character sprites and how primitive they currently are, holding no state whatsoever (they are essentially just engo Entities with rendering and animation components that are dinamically built based on their action frames. This is how it currently looks like:

<p align="center"">
<img src="https://user-images.githubusercontent.com/696982/112054796-c84d4700-8b34-11eb-823b-2dd9ecd93684.gif" width="45%" />
<img src="https://user-images.githubusercontent.com/696982/112075592-8f729980-8b57-11eb-9253-87c5d3301131.gif" width="45%" />
</p>

**Comment by drgomesp** [comment]
So this is the current state of the implementation:

![problem](https://user-images.githubusercontent.com/696982/112697730-f8fbec00-8e66-11eb-95e3-75ec0354c0f2.gif)

Animations are working properly, and directions too, and the only issue seems to be when using the flipped sprites (mirrored effect), which causes the sprite to appear to move out of position because of some unknown bug currently.

I'm guessing the issue is related to not using the sprite offsets properly, and the whole rendering mechanism. If I try to overcome this by compensating the offset on the sprite position, the position keeps being incremented by the offset on every update iteration, which makes the entity move out of position as well. 

Maybe I should find an alternative solution to this, such as controlling the state of whether the sprite needs offset compensation on its position or not, based on a combination of checks on the character state, direction and the animation that's playing too.

**Comment by drgomesp** [comment]
Problem fixed by offseting the character position by the width of the texture. Quite easy.

![fixed!](https://user-images.githubusercontent.com/696982/112709385-e221bd80-8e97-11eb-8738-77d446f624aa.gif)

**Comment by drgomesp** [comment]
Properly applying offset on char position:

![WALKS](https://user-images.githubusercontent.com/696982/112721391-423d5180-8ee2-11eb-87db-58fd94a36803.gif)

**Comment by GreenStage** [comment]
Hi, can I have a go at this?

**Comment by drgomesp** [comment]
Hey @GreenStage ! Happy to see your interest in contributing!

Keep in mind the current state of sprite rendering is somewhat close to this now:

![WALKS PERFECTLY](https://user-images.githubusercontent.com/696982/116827596-34798c80-ab70-11eb-91cf-433c50bd403b.gif)
![WALKING BASIC](https://user-images.githubusercontent.com/696982/116827610-45c29900-ab70-11eb-8508-e0f9d2030545.gif)

Currently, we're in need of 1) testing to see if all character actions are properly rendered (i have extensively tested with Idle and Walking actions, the others are missing testing so far) and actually implement the missing ones, as well as 2) the other character attachments that need to be rendered (upper, mid and bottom head gears and weapons).

Feel free to have a go at it, and join our Discord at https://discord.gg/GvKz2pYm in case you might have any questions or anything worth discussing over.

Cheers!

**Comment by drgomesp** [comment]
Closing this in favour of #2 and the others to come (more specific issues are better than general ones, like this).
